
server:
    port: ${PORT:4444}

spring:
  application:
    name: sinapps-publisher

  cloud:
    stream:
      bindings:
        input:
          destination: sinapps
          group: pusher

  rabbitmq:
    host: ${RABBIT_HOST:localhost}

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:9999}/eureka/
  instance:
    appname: ${spring.application.name}
    preferIpAddress: true
