
server:
  port: ${PORT:2222}

spring:
  application:
    name: itex-publisher

  cloud:
    stream:
      bindings:
        input:
          destination: itex
          group: pusher

  rabbitmq:
    host: ${RABBIT_HOST:localhost}

eureka:
  instance:
    appname: ${spring.application.name}
    preferIpAddress: true

  client:
    enabled: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:9999}/eureka/
