
server:
    port: ${EUREKA_PORT:9999}

spring:
  application:
    name: registry
  thymeleaf:
    enabled: false

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
