
server:
    port: ${PORT:2222}

spring:
  application:
    name: itex-publisher

  cloud:
    stream:
      bindings:
        input:
          destination: itex
          group: pusher

  rabbitmq:
    host: ${RABBIT_HOST:localhost}

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:1000}/eureka/
  instance:
    appname: ${spring.application.name}
    preferIpAddress: true
