
server:
    port: ${PORT:1111}

spring:
  application:
    name: sinapps-poller

  cloud:
    stream:
      bindings:
        output:
          destination: itex

  rabbitmq:
    host: ${RABBIT_HOST:localhost}

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:9999}/eureka/
  instance:
    appname: ${spring.application.name}
    preferIpAddress: true
