
server:
  port: ${PORT:3333}

spring:
  application:
    name: itex-poller

  cloud:
    stream:
      bindings:
        output:
          destination: sinapps

  rabbitmq:
    host: ${RABBIT_HOST:localhost}

eureka:
  instance:
    appname: ${spring.application.name}
    preferIpAddress: true

  client:
    enabled: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:9999}/eureka/
